config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :orders
  resources :customers
  resources :categories
  resources :provinces

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  
  has_many :orders
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  
  has_many :line_items
  has_many :products, through: :line_items
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  
  has_many :line_items
  has_many :orders, through: :line_items
  has_attached_file :image
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base

  private

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base

  private

    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :address, :city, :province_id, :country, :postal_code, :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  private

    def order_params
      params.require(:order).permit(:status, :customer_id, :pst_rate, :gst_rate, :hst_rate)
    end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base

  def index
    @products = Product.all
  end

  private

    def product_params
      params.require(:product).permit(:name, :description, :category_id, :price, :stock_quantity)
    end
end

app/controllers/provinces_controller.rb
class ProvincesController < InheritedResources::Base
  
  private
    
    def province_params
      params.require(:province).permit(:name, :pst, :gst, :hst)
    end
end

app/controllers/showcase_controller.rb
class ShowcaseController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/showcase_helper.rb
module ShowcaseHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :province_id %><br>
    <%= f.number_field :province_id %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>City</th>
      <th>Province</th>
      <th>Country</th>
      <th>Postal code</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.address %></td>
        <td><%= customer.city %></td>
        <td><%= customer.province_id %></td>
        <td><%= customer.country %></td>
        <td><%= customer.postal_code %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Province:</strong>
  <%= @customer.province_id %>
</p>

<p>
  <strong>Country:</strong>
  <%= @customer.country %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @customer.postal_code %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/home/index.html.slim
h1 Sitemap
nav
  ul
    li: a[href="admin"] admin
    li = link_to 'Home', 'home#index'
    li: a[href="products"] Products
    li: a[href="categories"] Categories
    li: a[href="provinces"] Provinces
    li: a[href="Orders"] Orders
hr

== render @products

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :pst_rate %><br>
    <%= f.text_field :pst_rate %>
  </div>
  <div class="field">
    <%= f.label :gst_rate %><br>
    <%= f.text_field :gst_rate %>
  </div>
  <div class="field">
    <%= f.label :hst_rate %><br>
    <%= f.text_field :hst_rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Customer</th>
      <th>Pst rate</th>
      <th>Gst rate</th>
      <th>Hst rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.status %></td>
        <td><%= order.customer_id %></td>
        <td><%= order.pst_rate %></td>
        <td><%= order.gst_rate %></td>
        <td><%= order.hst_rate %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer_id %>
</p>

<p>
  <strong>Pst rate:</strong>
  <%= @order.pst_rate %>
</p>

<p>
  <strong>Gst rate:</strong>
  <%= @order.gst_rate %>
</p>

<p>
  <strong>Hst rate:</strong>
  <%= @order.hst_rate %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class"field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, @categories, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock_quantity %><br>
    <%= f.number_field :stock_quantity %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.input :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.slim
.product.left
  h1 = product.name
  p = product.description
  p = number_to_currency(product.price)
  p = product.stock_quantity
  p = product.category.name

app/views/products/_products.html.slim
.product.left
  h1 = product.name
  p = product.description
  p = number_to_currency(product.price)
  p = product.stock_quantity
  p = product.category.name

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.slim
h1 Products Listing

table
  thead
      th Name
      th Description
      th Category
      th Price
      th Stock quantity
      th colspan="3"

  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = product.description
        - if product.category.present?
          td = product.category.name
        - end
        td = product.price
        td = product.stock_quantity
        td = link_to 'Show', product
        td = link_to 'Edit', edit_product_path(product)
        td = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Product', new_product_path

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Stock quantity:</strong>
  <%= @product.stock_quantity %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>